### ISSUE TITLE
Hey, it's me David

### ISSUE THREAD

**Issue by massimo1220** [mydicebot/mydicebot.github.io#137]

**Comment by DevStar0202** [comment]
this is my website. http://david.c1.biz

**Comment by DevStar0202** [comment]
hi

**Comment by DevStar0202** [comment]
Oh sorry
http://david0202.c1.biz

**Comment by DevStar0202** [comment]
![image](https://user-images.githubusercontent.com/111621165/193925026-db0c0b99-ffde-42b6-b922-6eb20f853508.png)

**Comment by DevStar0202** [comment]
are you there?
